name: CP
version: 0.1.0.0
synopsis: Compositional Programming
description: Please see README.md
category: Language
author: Anonymous
maintainer: anonymous@example.com
license: BSD3
dependencies:
  - base >=4.7 && <5
  - mtl
  - haskeline
  - array
  - containers
  - protolude >= 0.2
  - text
  - filepath
  - directory
  - megaparsec >= 6.0
  - scientific
  - prettyprinter
  - repline

ghc-options:
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-name-shadowing
  - -fwarn-incomplete-patterns
  - -Wincomplete-record-updates

library:
  source-dirs: src
  exposed-modules:
    - CP.Parser.Parser
    - CP.Environment
    - CP.Common
    - CP.PrettyPrint
    - CP.Source.Syntax
    - CP.Source.Subtyping
    - CP.Source.TypeCheck
    - CP.Source.Desugar
    - CP.Target.Syntax
    - CP.Target.Eval
    - CP.Util
    - CP
  dependencies:
    - unbound-generics

executables:
  cp-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - CP

tests:
  cp-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty >=0.11.1
      - tasty-hspec >=1.1.3.1
      - CP
